# Archivo de configuración para pyntegritydb

# Umbrales por defecto que se aplicarán a todas las tablas
# a menos que se especifique lo contrario.
thresholds:
  default:
    # La tasa de validez debe ser al menos del 99.5%
    validity_rate: 0.995
    
    # La tasa de filas huérfanas no debe superar el 0.5%
    orphan_rate: 0.005

  # Umbrales específicos para tablas críticas.
  # Estos sobrescriben los valores por defecto.
  tables:
    orders:
      # La tabla 'orders' es crítica, no se aceptan errores.
      validity_rate: 1.0
      orphan_rate: 0.0
      
    logs:
      # En la tabla 'logs' somos más permisivos.
      validity_rate: 0.95