name: Ejecutar Pruebas

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
            
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
            
      - name: Instalar dependencias
        run: pip install -e ".[dev]"

      - name: Ejecutar pruebas y generar reporte de cobertura
        run: pytest --cov=pyntegritydb --cov-report=xml

      - name: Verificar que el archivo de cobertura existe
        run: ls -l
            
      - name: Subir paquete a Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOVE_TOKEN }}
          verbose: true
          slug: ${{ github.repository }}
          override_branch: ${{ github.ref_name }}